---
title: "Untitled"
output: html_document
---

```{r}

if(!require(dplyr)){install.packages("base")}
if(!require(dplyr)){install.packages("rpart")}
if(!require(dplyr)){install.packages("WeightedROC")}
if(!require(dplyr)){install.packages("rpart.plot")}
#library(dplyr)
#library(ggplot2)
library(WeightedROC)
library(rpart)
library(rpart.plot)
library(base)

```


```{r setup, include=FALSE}
#import data
highDim <- read.csv("../data/highDim_dataset.csv")
lowDim <- read.csv("../data/lowDim_dataset.csv")
```

1 treatment indicator variable (A) and 1 continuous response variable (Y ).






```{r}
# data pre-processing
# features are the predictors: V1 - Vp
# column 1 is the response Y
# column 2 is the treatment A
feature_train_high = highDim[, -1:-2]
label_train_high = highDim[, 2]
feature_train_low = lowDim[, -1:-2]
label_train_low = lowDim[, 2]

```

#Propensity Score Estimation

```{r}
# imbalanced dataset requires weights 
# to be used in the trained model

weights_high <- rep(NA, length(highDim$A))
for (v in unique(highDim$A)){
  weights_high[highDim$A == v] = 0.5 * length(highDim$A) / length(highDim$A[highDim$A == v])
}


weights_low <- rep(NA, length(lowDim$A))
for (v in unique(lowDim$A)){
  weights_low[lowDim$A == v] = 0.5 * length(lowDim$A) / length(lowDim$A[lowDim$A == v])
}

```

```{r}
#propensity score estimate using regression tree for high dimension dataset
start.time_propensity_score_high <- Sys.time()

# create tree model for high dimensional data with best cp parameter
Reg_tree_high <- rpart(A ~ . - Y, method = "class", data = highDim)

# calculate propensity scores
propensity_score_high <- predict(Reg_tree_high, newdata = highDim[, -2], type = "prob")[, 2]

end.time_propensity_score_high <- Sys.time()
time_propensity_score_high <- end.time_propensity_score_high - start.time_propensity_score_high
time_propensity_score_high

```
```{r}
#ploy regression tree
rpart.plot(Reg_tree_high, type = 1, digits = 3, fallen.leaves = TRUE)

```

```{r}
#propensity score estimate using regression tree for low dimension dataset
start.time_propensity_score_low <- Sys.time()

# create tree model for low dimensional data with best cp parameter
Reg_tree_low <- rpart(A ~ . - Y, method = "class", data = lowDim)

# calculate propensity scores
propensity_score_low <- predict(Reg_tree_low, newdata = lowDim[, -2], type = "prob")[, 2]

end.time_propensity_score_low <- Sys.time()
time_propensity_score_low <- end.time_propensity_score_low - start.time_propensity_score_low
time_propensity_score_low
```
```{r}
#ploy regression tree
rpart.plot(Reg_tree_low, type = 1, digits = 3, fallen.leaves = TRUE)

```


#ATE Estimation

#### Stratification
```{r}
##choose k=3 strata
K = 3
strata <- seq(0, 1, by = 1/K)

```

```{r}
start.time_stratification_high <- Sys.time()

highDim <- cbind(highDim, propensity_score_high)
stratum_values_high <- rep(NA, length(strata))
  
for (i in 1:length(strata)){
  stratum_values_high[i] <- quantile(propensity_score_high, strata[i])
}

# values of strata for high data
stratum_values_high

highDim$stratum_class_high <- rep(NA, nrow(highDim))

# assign stratum class to each observation
for (i in 1:nrow(highDim)){
  if ((stratum_values_high[1] <= highDim$propensity_score_high[i]) & 
      (highDim$propensity_score_high[i] < stratum_values_high[2])) {
    highDim$stratum_class_high[i] <- 1
  } else if ((stratum_values_high[2] <= highDim$propensity_score_high[i]) & 
             (highDim$propensity_score_high[i] < stratum_values_high[3])) {
    highDim$stratum_class_high[i] <- 2
  } else if ((stratum_values_high[3] <= highDim$propensity_score_high[i]) & 
             (highDim$propensity_score_high[i] <= stratum_values_high[4])) {
    highDim$stratum_class_high[i] <- 3 
  }
}

summary_high = expand.grid(
  A = c(0, 1), 
  stratum = seq(1, K, by = 1), 
  n = NA, 
  prop = NA, 
  avg_y = NA
)

for (i in 1:nrow(summary_high)) {
  subset <- highDim[(highDim$A == summary_high$A[i]) & 
                      (highDim$stratum_class_high == summary_high$stratum[i]), ]
  summary_high$n[i] = nrow(subset)
  summary_high$prop[i] = summary_high$n[i]/nrow(highDim)
  summary_high$avg_y[i] = mean(subset$Y)
}


for (i in 1:nrow(summary_high)) {
  if (is.nan(summary_high$avg_y[i]) == TRUE) {
    summary_high$avg_y[i] <- 0 
  }
}

# this table records the mean response in each stratum; needed for stratification
summary_high

stratum_propensity_high <- summary_high %>% group_by(stratum) %>% summarise(sum = sum(n)/nrow(highDim))

# this table records the proportions for each stratum; also needed for stratification
stratum_propensity_high

ATE_stratification_high = stratum_propensity_high$sum[1]*(summary_high$avg_y[2] - summary_high$avg_y[1]) + 
  stratum_propensity_high$sum[2]*(summary_high$avg_y[4] - summary_high$avg_y[3]) + 
  stratum_propensity_high$sum[3]*(summary_high$avg_y[6] - summary_high$avg_y[5])

ATE_stratification_high

end.time_stratification_high <- Sys.time()
time_stratification_high <- end.time_stratification_high - start.time_stratification_high
time_stratification_high
```
